@Endpoint = http://localhost:5036/api

GET {{Endpoint}}/patients/pat
Accept: application/json

###-------------------------------------Patients-----------------------------------------

###Get patients
# @name patients
GET {{Endpoint}}/patients
Accept: application/json


###Get single patient
GET {{Endpoint}}/patients/{{patients.response.body.$[0].id}}
Accept: application/json


### create patient
POST {{Endpoint}}/patients
Content-Type: application/json

{
    "firstName": "Oleh",
    "lastName": "Datsko"
}

### update patient
PUT {{Endpoint}}/patients
Content-Type: application/json

{
    "id": "687ea732-371a-4b3e-9b50-cb107d4e5140",
    "firstName": "Anna",
    "lastName": "Datsko",
    "rowVersion": ""
}

###Delete patient
POST {{Endpoint}}/patients/687ea732-371a-4b3e-9b50-cb107d4e5140/discharge
Accept: application/json

###-------------------------------------Departments-----------------------------------------

###Get departments
# @name departments
Get {{Endpoint}}/departments
Accept: application/json

###Get department patients
# @name deppatients
Get {{Endpoint}}/departments/{{departments.response.body.$[1].id}}/patients
Accept: application/json


###Get department
# @name departmentToEdit
Get {{Endpoint}}/departments/{{departments.response.body.$[0].id}}
Accept: application/json


###Create department
POST {{Endpoint}}/departments
Content-Type: application/json

{
    "shortName": "IRM",
    "longName": "Intermediate"
}


###Update departments
PUT {{Endpoint}}/departments
Content-Type: application/json

{
    "id": "9f09dce0-f0c8-4560-8a24-916ea106e981",
    "shortName": "TestTestTestTestTestTestTestTestTest",
    "longName": "test1",
    "rowVersion": "/yn33BlgeAQ="
}


###Delete departments
DELETE {{Endpoint}}/departments/{{departmentToEdit.response.body.$.id}}
Accept: application/json